<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 0.8.0-alpha
 * FormDin Version: 4.2.5-alpha
 * 
 * System educ created in: 2018-06-27 11:06:14
 */
//Constantes e configurações
require_once('classes/ServidorConfig.class.php');

require_once('includes/constantes.php');
require_once('includes/config_conexao.php');

//FormDin version: 4.2.5
require_once('../base/classes/webform/TApplication.class.php');
require_once('controllers/autoload_migrajoomla.php');
require_once('dao/autoload_migrajoomla_dao.php');


$app = new TApplication(); // criar uma instancia do objeto aplicacao
$app->setTitle(SYSTEM_NAME);
$app->setSubtitle(SYSTEM_NAME_SUB);
$app->setSigla(SYSTEM_ACRONYM);
$app->setVersionSystem(SYSTEM_VERSION);
$app->setUnit('Secretaria de Tecnologia da Informação - STI - (2018)');


//Para testar com outro login basta informar o login desejado
define('SYSTEM_USER' , ServerHelper::get('PHP_AUTH_USER'));
$app->setLoginInfo(SYSTEM_USER);
//Acesso::usuarioAutorizado(SYSTEM_USER);

$app->setMainMenuFile('includes/menu.php');
//$app->setHeaderContent('index_header.php');
$app->setImgLogoPath('images/logo_mpdft.png');
$app->setWaterMark('images/bg_transparencia.jpg');


$app->run();
?>