<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.10.1-alpha
 * FormDin Version: 4.7.9-alpha
 * 
 * System migrajoomla created in: 2019-12-03 19:58:52
 */
class J25_modulesDAO 
{

    private static $sqlBasicSelect = 'select
                                      id
                                     ,title
                                     ,note
                                     ,content
                                     ,ordering
                                     ,position
                                     ,checked_out
                                     ,checked_out_time
                                     ,publish_up
                                     ,publish_down
                                     ,published
                                     ,module
                                     ,access
                                     ,showtitle
                                     ,params
                                     ,client_id
                                     ,language
                                     from '.J25_DB.'.'.J25_DBID.'modules ';

    private $tpdo = null;

    public function __construct($tpdo=null)
    {
        FormDinHelper::validateObjTypeTPDOConnectionObj($tpdo,__METHOD__,__LINE__);
        if( empty($tpdo) ){
            $tpdo = New TPDOConnectionObj();
        }
        $this->setTPDOConnection($tpdo);
    }
    public function getTPDOConnection()
    {
        return $this->tpdo;
    }
    public function setTPDOConnection($tpdo)
    {
        FormDinHelper::validateObjTypeTPDOConnectionObj($tpdo,__METHOD__,__LINE__);
        $this->tpdo = $tpdo;
    }
    private function processWhereGridParameters( $whereGrid )
    {
        $result = $whereGrid;
        if ( is_array($whereGrid) ){
            $where = ' 1=1 ';
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'ID', SqlHelper::SQL_TYPE_NUMERIC);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'TITLE', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'NOTE', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'CONTENT', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'ORDERING', SqlHelper::SQL_TYPE_NUMERIC);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'POSITION', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'CHECKED_OUT', SqlHelper::SQL_TYPE_NUMERIC);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'CHECKED_OUT_TIME', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'PUBLISH_UP', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'PUBLISH_DOWN', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'PUBLISHED', SqlHelper::SQL_TYPE_NUMERIC);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'MODULE', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'ACCESS', SqlHelper::SQL_TYPE_NUMERIC);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'SHOWTITLE', SqlHelper::SQL_TYPE_NUMERIC);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'PARAMS', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'CLIENT_ID', SqlHelper::SQL_TYPE_NUMERIC);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'LANGUAGE', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $result = $where;
        }
        return $result;
    }
    //--------------------------------------------------------------------------------
    public function selectById( $id )
    {
        FormDinHelper::validateIdIsNumeric($id,__METHOD__,__LINE__);
        $values = array($id);
        $sql = self::$sqlBasicSelect.' where id = ?';
        $result = $this->tpdo->executeSql($sql, $values);
        return $result;
    }
    //--------------------------------------------------------------------------------
    public function selectCount( $where=null )
    {
        $where = $this->processWhereGridParameters($where);
        $sql = 'select count(id) as qtd from '.J25_DB.'.'.J25_DBID.'modules ';
        $sql = $sql.( ($where)? ' where '.$where:'');
        $result = $this->tpdo->executeSql($sql);
        return $result['QTD'][0];
    }
    //--------------------------------------------------------------------------------
    public function selectAllPagination( $orderBy=null, $where=null, $page=null,  $rowsPerPage= null )
    {
        $rowStart = SqlHelper::getRowStart($page,$rowsPerPage);
        $where = $this->processWhereGridParameters($where);

        $sql = self::$sqlBasicSelect
        .( ($where)? ' where '.$where:'')
        .( ($orderBy) ? ' order by '.$orderBy:'')
        .( ' LIMIT '.$rowStart.','.$rowsPerPage);

        $result = $this->tpdo->executeSql($sql);
        return $result;
    }
    //--------------------------------------------------------------------------------
    public function selectAll( $orderBy=null, $where=null )
    {
        $where = $this->processWhereGridParameters($where);
        $sql = self::$sqlBasicSelect
        .( ($where)? ' where '.$where:'')
        .( ($orderBy) ? ' order by '.$orderBy:'');

        $result = $this->tpdo->executeSql($sql);
        return $result;
    }
    //--------------------------------------------------------------------------------
    public function insert( J25_modulesVO $objVo )
    {
        $values = array(  $objVo->getTitle() 
                        , $objVo->getNote() 
                        , $objVo->getContent() 
                        , $objVo->getOrdering() 
                        , $objVo->getPosition() 
                        , $objVo->getChecked_out() 
                        , $objVo->getChecked_out_time() 
                        , $objVo->getPublish_up() 
                        , $objVo->getPublish_down() 
                        , $objVo->getPublished() 
                        , $objVo->getModule() 
                        , $objVo->getAccess() 
                        , $objVo->getShowtitle() 
                        , $objVo->getParams() 
                        , $objVo->getClient_id() 
                        , $objVo->getLanguage() 
                        );
        $sql = 'insert '.J25_DB.'.'.J25_DBID.'modules  (
                                 title
                                ,note
                                ,content
                                ,ordering
                                ,position
                                ,checked_out
                                ,checked_out_time
                                ,publish_up
                                ,publish_down
                                ,published
                                ,module
                                ,access
                                ,showtitle
                                ,params
                                ,client_id
                                ,language
                                ) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)';
        $result = $this->tpdo->executeSql($sql, $values);
        $result = $this->tpdo->getLastInsertId();
        return intval($result);
    }
    //--------------------------------------------------------------------------------
    public function update ( J25_modulesVO $objVo )
    {
        $values = array( $objVo->getTitle()
                        ,$objVo->getNote()
                        ,$objVo->getContent()
                        ,$objVo->getOrdering()
                        ,$objVo->getPosition()
                        ,$objVo->getChecked_out()
                        ,$objVo->getChecked_out_time()
                        ,$objVo->getPublish_up()
                        ,$objVo->getPublish_down()
                        ,$objVo->getPublished()
                        ,$objVo->getModule()
                        ,$objVo->getAccess()
                        ,$objVo->getShowtitle()
                        ,$objVo->getParams()
                        ,$objVo->getClient_id()
                        ,$objVo->getLanguage()
                        ,$objVo->getId() );
        $sql = 'update '.J25_DB.'.'.J25_DBID.'modules set 
                                 title = ?
                                ,note = ?
                                ,content = ?
                                ,ordering = ?
                                ,position = ?
                                ,checked_out = ?
                                ,checked_out_time = ?
                                ,publish_up = ?
                                ,publish_down = ?
                                ,published = ?
                                ,module = ?
                                ,access = ?
                                ,showtitle = ?
                                ,params = ?
                                ,client_id = ?
                                ,language = ?
                                where id = ?';
        $result = $this->tpdo->executeSql($sql, $values);
        return intval($result);
    }
    //--------------------------------------------------------------------------------
    public function delete( $id )
    {
        FormDinHelper::validateIdIsNumeric($id,__METHOD__,__LINE__);
        $values = array($id);
        $sql = 'delete from '.J25_DB.'.'.J25_DBID.'modules where id = ?';
        $result = $this->tpdo->executeSql($sql, $values);
        return $result;
    }
    //--------------------------------------------------------------------------------
    public function getVoById( $id )
    {
        FormDinHelper::validateIdIsNumeric($id,__METHOD__,__LINE__);
        $result = $this->selectById( $id );
        $result = \ArrayHelper::convertArrayFormDin2Pdo($result,false);
        $result = $result[0];
        $vo = new J16_modulesVO();
        $vo = \FormDinHelper::setPropertyVo($result,$vo);
        return $vo;
    }
}
?>