<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.10.1-alpha
 * FormDin Version: 4.7.9-alpha
 * 
 * System migrajoomla created in: 2019-12-03 19:58:52
 */
class J25_modulesVO
{
    private $id = null;
    private $title = null;
    private $note = null;
    private $content = null;
    private $ordering = null;
    private $position = null;
    private $checked_out = null;
    private $checked_out_time = null;
    private $publish_up = null;
    private $publish_down = null;
    private $published = null;
    private $module = null;
    private $access = null;
    private $showtitle = null;
    private $params = null;
    private $client_id = null;
    private $language = null;
    public function __construct( $id=null, $title=null, $note=null, $content=null, $ordering=null, $position=null, $checked_out=null, $checked_out_time=null, $publish_up=null, $publish_down=null, $published=null, $module=null, $access=null, $showtitle=null, $params=null, $client_id=null, $language=null ) {
        $this->setId( $id );
        $this->setTitle( $title );
        $this->setNote( $note );
        $this->setContent( $content );
        $this->setOrdering( $ordering );
        $this->setPosition( $position );
        $this->setChecked_out( $checked_out );
        $this->setChecked_out_time( $checked_out_time );
        $this->setPublish_up( $publish_up );
        $this->setPublish_down( $publish_down );
        $this->setPublished( $published );
        $this->setModule( $module );
        $this->setAccess( $access );
        $this->setShowtitle( $showtitle );
        $this->setParams( $params );
        $this->setClient_id( $client_id );
        $this->setLanguage( $language );
    }
    //--------------------------------------------------------------------------------
    public function setId( $strNewValue = null )
    {
        $this->id = $strNewValue;
    }
    public function getId()
    {
        return $this->id;
    }
    //--------------------------------------------------------------------------------
    public function setTitle( $strNewValue = null )
    {
        $this->title = $strNewValue;
    }
    public function getTitle()
    {
        return $this->title;
    }
    //--------------------------------------------------------------------------------
    public function setNote( $strNewValue = null )
    {
        $this->note = $strNewValue;
    }
    public function getNote()
    {
        return $this->note;
    }
    //--------------------------------------------------------------------------------
    public function setContent( $strNewValue = null )
    {
        $this->content = $strNewValue;
    }
    public function getContent()
    {
        return $this->content;
    }
    //--------------------------------------------------------------------------------
    public function setOrdering( $strNewValue = null )
    {
        $this->ordering = $strNewValue;
    }
    public function getOrdering()
    {
        return $this->ordering;
    }
    //--------------------------------------------------------------------------------
    public function setPosition( $strNewValue = null )
    {
        $this->position = $strNewValue;
    }
    public function getPosition()
    {
        return $this->position;
    }
    //--------------------------------------------------------------------------------
    public function setChecked_out( $strNewValue = null )
    {
        $this->checked_out = $strNewValue;
    }
    public function getChecked_out()
    {
        return $this->checked_out;
    }
    //--------------------------------------------------------------------------------
    public function setChecked_out_time( $strNewValue = null )
    {
        $this->checked_out_time = $strNewValue;
    }
    public function getChecked_out_time()
    {
        return $this->checked_out_time;
    }
    //--------------------------------------------------------------------------------
    public function setPublish_up( $strNewValue = null )
    {
        $this->publish_up = $strNewValue;
    }
    public function getPublish_up()
    {
        return $this->publish_up;
    }
    //--------------------------------------------------------------------------------
    public function setPublish_down( $strNewValue = null )
    {
        $this->publish_down = $strNewValue;
    }
    public function getPublish_down()
    {
        return $this->publish_down;
    }
    //--------------------------------------------------------------------------------
    public function setPublished( $strNewValue = null )
    {
        $this->published = $strNewValue;
    }
    public function getPublished()
    {
        return $this->published;
    }
    //--------------------------------------------------------------------------------
    public function setModule( $strNewValue = null )
    {
        $this->module = $strNewValue;
    }
    public function getModule()
    {
        return $this->module;
    }
    //--------------------------------------------------------------------------------
    public function setAccess( $strNewValue = null )
    {
        $this->access = $strNewValue;
    }
    public function getAccess()
    {
        return $this->access;
    }
    //--------------------------------------------------------------------------------
    public function setShowtitle( $strNewValue = null )
    {
        $this->showtitle = $strNewValue;
    }
    public function getShowtitle()
    {
        return $this->showtitle;
    }
    //--------------------------------------------------------------------------------
    public function setParams( $strNewValue = null )
    {
        $this->params = $strNewValue;
    }
    public function getParams()
    {
        return $this->params;
    }
    //--------------------------------------------------------------------------------
    public function setClient_id( $strNewValue = null )
    {
        $this->client_id = $strNewValue;
    }
    public function getClient_id()
    {
        return $this->client_id;
    }
    //--------------------------------------------------------------------------------
    public function setLanguage( $strNewValue = null )
    {
        $this->language = $strNewValue;
    }
    public function getLanguage()
    {
        return $this->language;
    }
    //--------------------------------------------------------------------------------
}
?>