<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.10.1-alpha
 * FormDin Version: 4.7.9-alpha
 * 
 * System migraj created in: 2019-11-22 19:23:21
 */
class J16_categoriesDAO 
{

    private static $sqlBasicSelect = 'select
                                      id
                                     ,asset_id
                                     ,parent_id
                                     ,lft
                                     ,rgt
                                     ,level
                                     ,path
                                     ,extension
                                     ,title
                                     ,alias
                                     ,note
                                     ,description
                                     ,published
                                     ,checked_out
                                     ,checked_out_time
                                     ,access
                                     ,params
                                     ,metadesc
                                     ,metakey
                                     ,metadata
                                     ,created_user_id
                                     ,created_time
                                     ,modified_user_id
                                     ,modified_time
                                     ,hits
                                     ,language
                                     from joomlainternet.j16_categories ';

    private $tpdo = null;

    public function __construct($tpdo=null)
    {
        FormDinHelper::validateObjTypeTPDOConnectionObj($tpdo,__METHOD__,__LINE__);
        if( empty($tpdo) ){
            $tpdo = New TPDOConnectionObj();
        }
        $this->setTPDOConnection($tpdo);
    }
    public function getTPDOConnection()
    {
        return $this->tpdo;
    }
    public function setTPDOConnection($tpdo)
    {
        FormDinHelper::validateObjTypeTPDOConnectionObj($tpdo,__METHOD__,__LINE__);
        $this->tpdo = $tpdo;
    }
    private function processWhereGridParameters( $whereGrid )
    {
        $result = $whereGrid;
        if ( is_array($whereGrid) ){
            $where = ' 1=1 ';
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'ID', SqlHelper::SQL_TYPE_NUMERIC);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'ASSET_ID', SqlHelper::SQL_TYPE_NUMERIC);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'PARENT_ID', SqlHelper::SQL_TYPE_NUMERIC);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'LFT', SqlHelper::SQL_TYPE_NUMERIC);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'RGT', SqlHelper::SQL_TYPE_NUMERIC);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'LEVEL', SqlHelper::SQL_TYPE_NUMERIC);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'PATH', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'EXTENSION', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'TITLE', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'ALIAS', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'NOTE', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'DESCRIPTION', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'PUBLISHED', SqlHelper::SQL_TYPE_NUMERIC);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'CHECKED_OUT', SqlHelper::SQL_TYPE_NUMERIC);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'CHECKED_OUT_TIME', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'ACCESS', SqlHelper::SQL_TYPE_NUMERIC);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'PARAMS', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'METADESC', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'METAKEY', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'METADATA', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'CREATED_USER_ID', SqlHelper::SQL_TYPE_NUMERIC);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'CREATED_TIME', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'MODIFIED_USER_ID', SqlHelper::SQL_TYPE_NUMERIC);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'MODIFIED_TIME', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'HITS', SqlHelper::SQL_TYPE_NUMERIC);
            $where = SqlHelper::getAtributeWhereGridParameters($where, $whereGrid, 'LANGUAGE', SqlHelper::SQL_TYPE_TEXT_LIKE);
            $result = $where;
        }
        return $result;
    }
    //--------------------------------------------------------------------------------
    public function selectById( $id )
    {
        FormDinHelper::validateIdIsNumeric($id,__METHOD__,__LINE__);
        $values = array($id);
        $sql = self::$sqlBasicSelect.' where id = ?';
        $result = $this->tpdo->executeSql($sql, $values);
        return $result;
    }
    //--------------------------------------------------------------------------------
    public function selectCount( $where=null )
    {
        $where = $this->processWhereGridParameters($where);
        $sql = 'select count(id) as qtd from joomlainternet.j16_categories';
        $sql = $sql.( ($where)? ' where '.$where:'');
        $result = $this->tpdo->executeSql($sql);
        return $result['QTD'][0];
    }
    //--------------------------------------------------------------------------------
    public function selectAllPagination( $orderBy=null, $where=null, $page=null,  $rowsPerPage= null )
    {
        $rowStart = SqlHelper::getRowStart($page,$rowsPerPage);
        $where = $this->processWhereGridParameters($where);

        $sql = self::$sqlBasicSelect
        .( ($where)? ' where '.$where:'')
        .( ($orderBy) ? ' order by '.$orderBy:'')
        .( ' LIMIT '.$rowStart.','.$rowsPerPage);

        $result = $this->tpdo->executeSql($sql);
        return $result;
    }
    //--------------------------------------------------------------------------------
    public function selectAll( $orderBy=null, $where=null )
    {
        $where = $this->processWhereGridParameters($where);
        $sql = self::$sqlBasicSelect
        .( ($where)? ' where '.$where:'')
        .( ($orderBy) ? ' order by '.$orderBy:'');

        $result = $this->tpdo->executeSql($sql);
        return $result;
    }
    //--------------------------------------------------------------------------------
    public function insert( J16_categoriesVO $objVo )
    {
        $values = array(  $objVo->getAsset_id() 
                        , $objVo->getParent_id() 
                        , $objVo->getLft() 
                        , $objVo->getRgt() 
                        , $objVo->getLevel() 
                        , $objVo->getPath() 
                        , $objVo->getExtension() 
                        , $objVo->getTitle() 
                        , $objVo->getAlias() 
                        , $objVo->getNote() 
                        , $objVo->getDescription() 
                        , $objVo->getPublished() 
                        , $objVo->getChecked_out() 
                        , $objVo->getChecked_out_time() 
                        , $objVo->getAccess() 
                        , $objVo->getParams() 
                        , $objVo->getMetadesc() 
                        , $objVo->getMetakey() 
                        , $objVo->getMetadata() 
                        , $objVo->getCreated_user_id() 
                        , $objVo->getCreated_time() 
                        , $objVo->getModified_user_id() 
                        , $objVo->getModified_time() 
                        , $objVo->getHits() 
                        , $objVo->getLanguage() 
                        );
        $sql = 'insert into joomlainternet.j16_categories(
                                 asset_id
                                ,parent_id
                                ,lft
                                ,rgt
                                ,level
                                ,path
                                ,extension
                                ,title
                                ,alias
                                ,note
                                ,description
                                ,published
                                ,checked_out
                                ,checked_out_time
                                ,access
                                ,params
                                ,metadesc
                                ,metakey
                                ,metadata
                                ,created_user_id
                                ,created_time
                                ,modified_user_id
                                ,modified_time
                                ,hits
                                ,language
                                ) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)';
        $result = $this->tpdo->executeSql($sql, $values);
        $result = $this->tpdo->getLastInsertId();
        return intval($result);
    }
    //--------------------------------------------------------------------------------
    public function update ( J16_categoriesVO $objVo )
    {
        $values = array( $objVo->getAsset_id()
                        ,$objVo->getParent_id()
                        ,$objVo->getLft()
                        ,$objVo->getRgt()
                        ,$objVo->getLevel()
                        ,$objVo->getPath()
                        ,$objVo->getExtension()
                        ,$objVo->getTitle()
                        ,$objVo->getAlias()
                        ,$objVo->getNote()
                        ,$objVo->getDescription()
                        ,$objVo->getPublished()
                        ,$objVo->getChecked_out()
                        ,$objVo->getChecked_out_time()
                        ,$objVo->getAccess()
                        ,$objVo->getParams()
                        ,$objVo->getMetadesc()
                        ,$objVo->getMetakey()
                        ,$objVo->getMetadata()
                        ,$objVo->getCreated_user_id()
                        ,$objVo->getCreated_time()
                        ,$objVo->getModified_user_id()
                        ,$objVo->getModified_time()
                        ,$objVo->getHits()
                        ,$objVo->getLanguage()
                        ,$objVo->getId() );
        $sql = 'update joomlainternet.j16_categories set 
                                 asset_id = ?
                                ,parent_id = ?
                                ,lft = ?
                                ,rgt = ?
                                ,level = ?
                                ,path = ?
                                ,extension = ?
                                ,title = ?
                                ,alias = ?
                                ,note = ?
                                ,description = ?
                                ,published = ?
                                ,checked_out = ?
                                ,checked_out_time = ?
                                ,access = ?
                                ,params = ?
                                ,metadesc = ?
                                ,metakey = ?
                                ,metadata = ?
                                ,created_user_id = ?
                                ,created_time = ?
                                ,modified_user_id = ?
                                ,modified_time = ?
                                ,hits = ?
                                ,language = ?
                                where id = ?';
        $result = $this->tpdo->executeSql($sql, $values);
        return intval($result);
    }
    //--------------------------------------------------------------------------------
    public function delete( $id )
    {
        FormDinHelper::validateIdIsNumeric($id,__METHOD__,__LINE__);
        $values = array($id);
        $sql = 'delete from joomlainternet.j16_categories where id = ?';
        $result = $this->tpdo->executeSql($sql, $values);
        return $result;
    }
    //--------------------------------------------------------------------------------
    public function getVoById( $id )
    {
        FormDinHelper::validateIdIsNumeric($id,__METHOD__,__LINE__);
        $result = $this->selectById( $id );
        $result = \ArrayHelper::convertArrayFormDin2Pdo($result,false);
        $result = $result[0];
        $vo = new J16_categoriesVO();
        $vo = \FormDinHelper::setPropertyVo($result,$vo);
        return $vo;
    }
}
?>