<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.10.1-alpha
 * FormDin Version: 4.7.9-alpha
 * 
 * System migraj created in: 2019-11-22 18:12:06
 */
class J36_assetsVO
{
    private $id = null;
    private $parent_id = null;
    private $lft = null;
    private $rgt = null;
    private $level = null;
    private $name = null;
    private $title = null;
    private $rules = null;
    public function __construct( $id=null, $parent_id=null, $lft=null, $rgt=null, $level=null, $name=null, $title=null, $rules=null ) {
        $this->setId( $id );
        $this->setParent_id( $parent_id );
        $this->setLft( $lft );
        $this->setRgt( $rgt );
        $this->setLevel( $level );
        $this->setName( $name );
        $this->setTitle( $title );
        $this->setRules( $rules );
    }
    //--------------------------------------------------------------------------------
    public function setId( $strNewValue = null )
    {
        $this->id = $strNewValue;
    }
    public function getId()
    {
        return $this->id;
    }
    //--------------------------------------------------------------------------------
    public function setParent_id( $strNewValue = null )
    {
        $this->parent_id = $strNewValue;
    }
    public function getParent_id()
    {
        return $this->parent_id;
    }
    //--------------------------------------------------------------------------------
    public function setLft( $strNewValue = null )
    {
        $this->lft = $strNewValue;
    }
    public function getLft()
    {
        return $this->lft;
    }
    //--------------------------------------------------------------------------------
    public function setRgt( $strNewValue = null )
    {
        $this->rgt = $strNewValue;
    }
    public function getRgt()
    {
        return $this->rgt;
    }
    //--------------------------------------------------------------------------------
    public function setLevel( $strNewValue = null )
    {
        $this->level = $strNewValue;
    }
    public function getLevel()
    {
        return $this->level;
    }
    //--------------------------------------------------------------------------------
    public function setName( $strNewValue = null )
    {
        $this->name = $strNewValue;
    }
    public function getName()
    {
        return $this->name;
    }
    //--------------------------------------------------------------------------------
    public function setTitle( $strNewValue = null )
    {
        $this->title = $strNewValue;
    }
    public function getTitle()
    {
        return $this->title;
    }
    //--------------------------------------------------------------------------------
    public function setRules( $strNewValue = null )
    {
        $this->rules = $strNewValue;
    }
    public function getRules()
    {
        return $this->rules;
    }
    //--------------------------------------------------------------------------------
}
?>