<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.10.1-alpha
 * FormDin Version: 4.7.9-alpha
 * 
 * System migrajoomla created in: 2019-12-04 16:00:53
 */
class J39_content_frontpageVO
{
    private $content_id = null;
    private $ordering = null;
    public function __construct( $content_id=null, $ordering=null ) {
        $this->setContent_id( $content_id );
        $this->setOrdering( $ordering );
    }
    //--------------------------------------------------------------------------------
    public function setContent_id( $strNewValue = null )
    {
        $this->content_id = $strNewValue;
    }
    public function getContent_id()
    {
        return $this->content_id;
    }
    //--------------------------------------------------------------------------------
    public function setOrdering( $strNewValue = null )
    {
        $this->ordering = $strNewValue;
    }
    public function getOrdering()
    {
        return $this->ordering;
    }
    //--------------------------------------------------------------------------------
}
?>