<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 0.8.0-alpha
 * FormDin Version: 4.2.5-alpha
 * 
 * System educ created in: 2018-06-27 11:06:14
 */

if ( !function_exists( 'migrajoomla_autoload') ) {
	function migrajoomla_autoload( $class_name )	{
		require_once $class_name . '.class.php';
	}
spl_autoload_register('migrajoomla_autoload');
}