<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.10.1-alpha
 * FormDin Version: 4.7.9-alpha
 * 
 * System migraj created in: 2019-11-22 19:23:21
 */

defined('APLICATIVO') or die();

//--------- Inicio do Form ----------------
$frm = new TForm('Atualizar um artigo');
$frm->setFlat(true);
$frm->setMaximize(true);

$frm->addNumberField('ID', 'Id Artigo '.J25,8,true,0,null,null,null,null,false);

$frm->addButton('Migrar', null, 'Migrar', null, null, true, false);
$frm->addButton('Limpar', null, 'Limpar', null, null, false, false);

$acao = isset($acao) ? $acao : null;
switch( $acao ) {
    //--------------------------------------------------------------------------------
    case 'Migrar':
        try{            
            if ( $frm->validate() ) {
                $id = $frm->getFieldValue('ID');
                $listArtigos = array();
                $listArtigos[]=$id;
                $controller = new Migrar();
                $msg = $controller->artigosAtualizar($listArtigos);
                $frm->setMessage( $msg );                
            }
        }
        catch (DomainException $e) {
            $frm->addMessage( $e->getMessage() ); //addMessage evita o problema do setMessage
        }
        catch (Exception $e) {
            Mensagem::reportarLog($e);
            $frm->addMessage( $e->getMessage() ); //addMessage evita o problema do setMessage
        }
    break;
    //--------------------------------------------------------------------------------
    case 'Limpar':
        $frm->clearFields();
        break;
}

$frm->addHtmlField('gride');
$frm->show();

?>