<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 0.8.0-alpha
 * FormDin Version: 4.2.5-alpha
 * 
 * System educ created in: 2018-06-27 11:06:14
 */

$perfilBancoAdm  = ServidorConfig::getInstancia()->getPerfilAdm();

define('BANCO'   , $perfilBancoAdm['banco']);
define('HOST'    , $perfilBancoAdm['hostname']);
define('PORT'    , $perfilBancoAdm['port']);
define('DATABASE', $perfilBancoAdm['dbname']);
define('SCHEMA'  , '');
define('USUARIO' , $perfilBancoAdm['username']);
define('SENHA'   , $perfilBancoAdm['password']);
define('UTF8_DECODE'   , 0);

?>