<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 0.8.0-alpha
 * FormDin Version: 4.2.5-alpha
 * 
 * System educ created in: 2018-06-27 11:06:14
 */
$ambiente  = ServidorConfig::getInstancia()->getConfigParam('ambiente');
if( $ambiente == 'produção' || $ambiente == 'producao' ) {
    $ambiente = null;
}

define('SYSTEM_NAME'    , 'Migração do Joomla');
define('SYSTEM_NAME_SUB', $ambiente);
define('SYSTEM_ACRONYM' , 'migraj');
define('SYSTEM_VERSION' , '2.0.0');
define('APLICATIVO'     , SYSTEM_ACRONYM);

define('FORMDIN_VERSION_MIN_VERSION', '4.7.8');

if ( !defined('DS') ){ define('DS'   , DIRECTORY_SEPARATOR); }

?>